paths:
  /api/products:
    get:
      summary: Lista todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos con exito desde la base de datos.
        "500":
          description: Error interno del servidor.

